export const categories = [
  {
    id: 1,
    title: "T-shirts",
    img: "https://images.unsplash.com/photo-1583744946564-b52ac1c389c8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OHx8dCUyMHNoaXJ0fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
  },
  {
    id: 2,
    title: "Jeans",
    img: "https://images.pexels.com/photos/11068001/pexels-photo-11068001.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
  },
  {
    id: 3,
    title: "Shirts",
    img: "https://images.unsplash.com/photo-1607345366928-199ea26cfe3e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
  },
  {
    id: 4,
    title: "Dresses",
    img: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=746&q=80",
  },
];
export const men_section = [
  {
    id: 1,
    title: "Shirts",
    img: "https://images.unsplash.com/photo-1617508005454-578bcf78db14?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=764&q=80",
  },
  {
    id: 2,
    title: "T-shirts",
    img: "https://images.pexels.com/photos/9558233/pexels-photo-9558233.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
  },
  {
    id: 3,
    title: "Jeans",
    img: "https://images.unsplash.com/photo-1511105612320-2e62a04dd044?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=765&q=80",
  },
  {
    id: 4,
    title: "Ethnicwear",
    img: "https://images.pexels.com/photos/6687182/pexels-photo-6687182.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
  },
  {
    id: 5,
    title: "Footwear",
    img: "https://images.unsplash.com/photo-1560769629-975ec94e6a86?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=764&q=80",
  },
];
export const women_section = [
  {
    id: 1,
    title: "Shirts",
    img: "https://images.unsplash.com/photo-1608234807905-4466023792f5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=735&q=80",
  },
  {
    id: 2,
    title: "T-shirts",
    img: "https://images.pexels.com/photos/9558583/pexels-photo-9558583.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
  },
  {
    id: 3,
    title: "Jeans",
    img: "https://images.unsplash.com/photo-1603217192634-61068e4d4bf9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=735&q=80",
  },
  {
    id: 4,
    title: "Dresses",
    img: "https://images.unsplash.com/photo-1564957779922-6e601eda9548?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=764&q=80",
  },
  {
    id: 5,
    title: "Sarees",
    img: "https://images.pexels.com/photos/5704311/pexels-photo-5704311.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
  },
  {
    id: 6,
    title: "Handbags",
    img: "https://images.unsplash.com/photo-1614179689702-355944cd0918?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=735&q=80",
  },
];
export const products = [
  {
    id: 1,
    title: "Men Floral Printed Cotton Casual Shirt",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/14885648/2021/11/10/93f88b4a-b28d-49bb-999c-97fe8e6002461636521584570-Mast--Harbour-Men-Shirts-6411636521583818-1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "men",
    category: "Shirts",
    price: 999,
    real_price: 2499,
    discount: "60% OFF",
  },
  {
    id: 2,
    title: "Men Navy Blue Solid Formal Shirt",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/11530470/2020/3/6/f6cdb7c4-ffb0-4e20-8cef-337143050d321583472564794-DENNISON-Men-Navy-Blue-Comfort-Regular-Fit-Solid-Formal-Shir-1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "men",
    category: "Shirts",
    price: 799,
    real_price: 2499,
    discount: "68% OFF",
  },
  {
    id: 3,
    title: "Men Blue & Grey Checked Casual Shirt",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/11948758/2020/9/9/7eeb6638-0562-4235-8251-cfb8053f74101599635441510-Mast--Harbour-Men-Shirts-761599635439594-4.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "men",
    category: "Shirts",
    price: 1099,
    real_price: 2199,
    discount: "50% OFF",
  },
  {
    id: 4,
    title: "Men Green Slim Fit Opaque Cotton Casual Shirt",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/15770272/2021/10/9/61547be9-3641-49c2-ac9a-8aba9c1423f91633783087494KETCHMenGreenSlimFitOpaqueCasualShirt1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "men",
    category: "Shirts",
    price: 415,
    real_price: 1299,
    discount: "68% OFF",
  },
  {
    id: 5,
    title: "Men Maroon Geometrical Printed Slim Fit Formal Shirt",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/16322540/2022/1/28/12c43be2-083b-4b50-b246-76034cbb221c1643347431638-Arrow-Men-Maroon-Geometrical-Printed-Slim-Fit-Formal-Shirt-3-1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "men",
    category: "Shirts",
    price: 1599,
    real_price: 1999,
    discount: "20% OFF",
  },
  {
    id: 6,
    title: "Men Beige & Olive Green Slim Fit Printed Casual Shirt",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/10216033/2019/8/27/296b3f6a-f13b-4b99-9e02-a7c4afce32c91566901413315-The-Indian-Garage-Co-Men-Beige-Slim-Fit-Printed-Casual-Shirt-1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "men",
    category: "Shirts",
    price: 699,
    real_price: 1749,
    discount: "60% OFF",
  },
  {
    id: 7,
    title: "Women Pink Casual Shirt",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/15253608/2021/12/9/08fddc56-cf0a-4010-ad16-09ea47e123511639034307928-her-by-invictus-Women-Shirts-9201639034307323-1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "women",
    category: "Shirts",
    price: 559,
    real_price: 1398,
    discount: "60% OFF",
  },
  {
    id: 8,
    title: "Women Black Floral Printed Casual Shirt",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/16459164/2021/12/11/ceb09ba0-585b-4575-b8dc-5afbea1d29101639216913585MAGREWomenBlackFloralPrintedCasualShirt1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "women",
    category: "Shirts",
    price: 895,
    real_price: 1990,
    discount: "55% OFF",
  },
  {
    id: 9,
    title: "Women Green Checked High-Low Casual Shirt",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/15181536/2021/8/18/abc4ba8e-c364-4838-936e-1ccfab46bea71629273543973Shirts1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "women",
    category: "Shirts",
    price: 869,
    real_price: 2899,
    discount: "70% OFF",
  },
  {
    id: 10,
    title: "Women Drop-Shoulder Denim Crop Casual Shirt",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/15773440/2021/12/1/443ed85b-9986-41fb-ab2f-ee25ffe6966c1638361621567-Roadster-Women-Shirts-9921638361620962-1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "women",
    category: "Shirts",
    price: 719,
    real_price: 1599,
    discount: "55% OFF",
  },
  {
    id: 11,
    title: "Women White & Black Regular Fit Checked Casual Shirt",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/productimage/2020/7/16/19561e0a-90eb-482c-ab94-6a42bbc0e7601594853933391-1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "women",
    category: "Shirts",
    price: 999,
    real_price: 1999,
    discount: "50% OFF",
  },
  {
    id: 12,
    title: "Women Black & Silver Regular Fit Checked Casual Shirt",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/productimage/2021/5/3/62c0ff26-cbfc-4196-8392-ec70cc60e0bf1620058262466-1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "women",
    category: "Shirts",
    price: 1199,
    real_price: 1999,
    discount: "40% OFF",
  },
  {
    id: 13,
    title: "Men Teal Green Chest Print Round Neck Pure Cotton T-shirt",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/11900354/2020/10/8/a6318766-cbb7-4238-8a8f-f63faf4f03321602164298413etherMenTealGreenChestPrintRoundNeckT-shirt1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "men",
    category: "T-shirts",
    price: 349,
    real_price: 699,
    discount: "50% OFF",
  },
  {
    id: 14,
    title: "Men Red Solid Mandarin Collar T-shirt",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/11926516/2020/6/18/e3f07107-3bed-4f1a-8f31-c2bc71096f191592472408473-Roadster-Men-Red-Solid-Mandarin-Collar-T-shirt-7921592472407-1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "men",
    category: "T-shirts",
    price: 604,
    real_price: 1099,
    discount: "45% OFF",
  },
  {
    id: 15,
    title:
      "Jack Jones Men Olive Green Orange Printed Polo Collar Slim Fit Pure Cotton T-shirt",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/14818766/2021/10/27/260ed466-6922-4b14-9f14-4960aebc495f1635320144548-Jack--Jones-Men-Tshirts-5741635320144113-1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "men",
    category: "T-shirts",
    price: 849,
    real_price: 1699,
    discount: "50% OFF",
  },
  {
    id: 16,
    title: "Men Charcoal Grey Henley Neck T-shirt",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/15484116/2021/9/23/aa8520c1-8d41-446c-946f-5f829778b4b81632376436294-United-Colors-of-Benetton-Men-Tshirts-3961632376435774-1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "men",
    category: "T-shirts",
    price: 631,
    real_price: 1149,
    discount: "45% OFF",
  },
  {
    id: 17,
    title: "Men Off-White Pure Cotton Solid Lounge T-Shirt",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/productimage/2021/5/6/55059b0f-317f-4bd2-83b3-e4151b3f12541620279813295-1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "men",
    category: "T-shirts",
    price: 419,
    real_price: 599,
    discount: "30% OFF",
  },
  {
    id: 18,
    title: "Men Green Slim Fit Solid Polo Collar Pure Cotton T-shirt",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/13674580/2021/4/5/4b4235b8-64bf-4174-b7a7-877e9a5923921617607487234-WROGN-Men-Tshirts-3081617607486591-1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "men",
    category: "T-shirts",
    price: 749,
    real_price: 1399,
    discount: "45% OFF",
  },
  {
    id: 19,
    title: "Women Green & White Printed Drop-Shoulder Sleeves T-shirt",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/14928748/2021/11/9/043bfe8e-5c48-4bc4-b85d-0ddf26fd54c61636443326735-ether-Women-Tshirts-8671636443326032-1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "women",
    category: "T-shirts",
    price: 404,
    real_price: 899,
    discount: "55% OFF",
  },
  {
    id: 20,
    title: "Women Peach-Coloured Printed Round Neck Pure Cotton T-shirt",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/10964510/2021/1/20/477ef292-68aa-4329-84f8-54177daa8f761611122492957-Roadster-Women-Peach-Coloured-Printed-Round-Neck-T-shirt-166-1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "women",
    category: "T-shirts",
    price: 314,
    real_price: 899,
    discount: "65% OFF",
  },
  {
    id: 21,
    title: "Women Navy Blue Solid V-Neck Pure Cotton T-shirt",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/12645748/2020/12/9/827c8b31-9bf5-4ca4-a58c-52302804da631607512655758-Chemistry-Women-Tshirts-1171607512653628-1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "women",
    category: "T-shirts",
    price: 299,
    real_price: 599,
    discount: "50% OFF",
  },
  {
    id: 22,
    title: "Women Peach-Coloured & Blue Printed Pure Cotton T-shirt",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/15288054/2021/12/22/e268db27-67b5-43c3-b200-1f89794fa9dd1640156842006-Mast--Harbour-Women-Pink--Blue-Printed-Pure-Cotton-T-shirt-8-1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "women",
    category: "T-shirts",
    price: 319,
    real_price: 799,
    discount: "60% OFF",
  },
  {
    id: 23,
    title: "Women Grey Melange & Pink Colourblocked Round Neck T-shirt",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/11892356/2020/8/11/c4fb32f5-17a2-4a21-8b61-5ce9f0be223e1597146896891-Roadster-Women-Tshirts-4281597146895475-1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "women",
    category: "T-shirts",
    price: 404,
    real_price: 899,
    discount: "55% OFF",
  },
  {
    id: 24,
    title: "Mast Harbour Women Black Solid Round Neck Crop Pure Cotton T-shirt",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/2490935/2018/5/28/b922c330-1a73-473c-8f16-3a0f2476cde21527502377637-Mast--Harbour-Women-Black-Solid-Round-Neck-T-shirt-9271527502376327-1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "women",
    category: "T-shirts",
    price: 349,
    real_price: 699,
    discount: "50% OFF",
  },
  {
    id: 25,
    title: "Men Grey Slim Fit Mid-Rise Clean Look Stretchable Jeans",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/11358898/2020/9/22/69252de7-8ca7-4f0c-8f4a-59f5bb887aa11600759328050-WROGN-Men-Grey-Slim-Fit-Mid-Rise-Clean-Look-Stretchable-Jean-2.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "men",
    category: "Jeans",
    price: 1149,
    real_price: 2299,
    discount: "50% OFF",
  },
  {
    id: 26,
    title:
      "Men Navy Blue Skinny Fit Mid-Rise Mildly Distressed Stretchable Jeans",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/13077168/2021/1/27/030f8ffe-1d65-41b8-ab73-46e87634bea01611744761539-Mast--Harbour-Men-Jeans-4071611744759222-1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "men",
    category: "Jeans",
    price: 749,
    real_price: 1499,
    discount: "50% OFF",
  },
  {
    id: 27,
    title:
      "U S Polo Assn Denim Co Men Grey Skinny Fit Light Fade Stretchable Jeans",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/15321338/2021/11/15/addc4a53-377e-419e-8b90-42a2154228501636951844084-US-Polo-Assn-Denim-Co-Men-Jeans-4061636951843364-2.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "men",
    category: "Jeans",
    price: 1439,
    real_price: 2399,
    discount: "40% OFF",
  },
  {
    id: 28,
    title: "Men Olive Green Carrot Fit Stretchable Jeans",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/15135010/2021/12/29/f080d8bb-310a-4eff-a930-182c6d54dbbe1640758032875-Mast--Harbour-Men-Olive-Green-Carrot-Stretchable-Jeans-22016-1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "men",
    category: "Jeans",
    price: 1049,
    real_price: 2099,
    discount: "50% OFF",
  },
  {
    id: 29,
    title: "Men Blue MATT Slim FitLow-Rise Light Fade Stretchable Jeans",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/16597530/2022/1/7/7ec685eb-1144-4541-a630-9af70b798b481641535889177-Louis-Philippe-Jeans-Men-Jeans-8781641535888509-1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "men",
    category: "Jeans",
    price: 2249,
    real_price: 2999,
    discount: "25% OFF",
  },
  {
    id: 30,
    title: "Men White Slim Fit Mid-Rise Slash Knee Stretchable Jeans",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/13335512/2021/1/13/bf7c8572-09ad-416f-b3b0-cd062fc721e61610516985733-Urbano-Fashion-Mens-White-Knee-Slit-Distressed-Jeans-Stretch-2.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "men",
    category: "Jeans",
    price: 899,
    real_price: 1799,
    discount: "50% OFF",
  },
  {
    id: 31,
    title: "Women Blue Faded Slouchy Crop Jeans",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/14925778/2021/9/14/ea4d7c27-b760-48f2-8cbd-73854d12dc7f1631611725274-Roadster-Women-Blue-Faded-Slouchy-Crop-Jeans-259163161172432-1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "women",
    category: "Jeans",
    price: 899,
    real_price: 1499,
    discount: "40% OFF",
  },
  {
    id: 32,
    title: "Women Blue Skinny Fit High-Rise Clean Look Stretchable Denim Jeans",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/10666988/2021/10/28/652067f9-2761-4a40-888c-1a42daf3c9091635392987563-DOLCE-CRUDO-Women-Blue-Skinny-Fit-High-Rise-Clean-Look-Stret-2.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "women",
    category: "Jeans",
    price: 1149,
    real_price: 2299,
    discount: "50% OFF",
  },
  {
    id: 33,
    title: "Women Black Slim Fit Mid-Rise Clean Look Stretchable Jeans",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/7463808/2018/9/22/2ff5bfb2-d5fd-4134-82c5-7113af0ffd581537596261337-HSWDXL04032-231537596261207-2.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "women",
    category: "Jeans",
    price: 839,
    real_price: 1999,
    discount: "58% OFF",
  },
  {
    id: 34,
    title:
      "Women Blue Relaxed Fit Mid-Rise Highly Distressed Stretchable Jeans",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/productimage/2020/10/9/ecc2cb42-b82d-4e71-bb4b-7645841106631602201633073-1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "women",
    category: "Jeans",
    price: 1247,
    real_price: 2599,
    discount: "52% OFF",
  },
  {
    id: 35,
    title: "Women Charcoal Jean Boyfriend Fit High-Rise Heavy Fade Jeans",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/17039390/2022/2/3/b9805338-47ab-4cf7-af26-a41851d606de1643891554146KottyWomenCharcoalJeanBoyfriendFitHigh-RiseHeavyFadeJeans2.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "women",
    category: "Jeans",
    price: 899,
    real_price: 1999,
    discount: "55% OFF",
  },
  {
    id: 36,
    title: "Women Blue Flared High-Rise Light Fade Jeans",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/productimage/2021/6/29/31f57c80-e7f2-4d6b-9d44-a2a796e361891624946747045-3.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "women",
    category: "Jeans",
    price: 2029,
    real_price: 2899,
    discount: "30% OFF",
  },
  {
    id: 37,
    title: "Blue & White Cotton Ethnic Motif Print Midi A-Line Dress",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/13938470/2021/4/3/1c42381b-985e-45f7-85c3-b19a41639d7f1617436396055TshirtsUnitedColorsofBenettonMenTshirtsUnitedColorsofBenetto1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "women",
    category: "Dresses",
    price: 1133,
    real_price: 2699,
    discount: "58% OFF",
  },
  {
    id: 38,
    title: "Women Blue Printed A-Line Dress",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/2519185/2018/2/23/11519379839915-Sera-Womens-Western-wear-Blue-Fleared-sleeves-A-line-dress-281519379839711-1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "women",
    category: "Dresses",
    price: 797,
    real_price: 1594,
    discount: "50% OFF",
  },
  {
    id: 39,
    title: "Red Floral Printed Fit and Flare Dress",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/productimage/2019/1/1/c514a5a5-d9d2-4aa8-a190-1fc5260e681f1546364979279-1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "women",
    category: "Dresses",
    price: 809,
    real_price: 1799,
    discount: "55% OFF",
  },
  {
    id: 40,
    title: "Women Blue Embroidered Denim Shirt Dress",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/productimage/2018/12/7/e4d4754c-2fa5-41ba-81fd-6eb163cdf8331544206974378-1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "women",
    category: "Dresses",
    price: 1079,
    real_price: 3599,
    discount: "70% OFF",
  },
  {
    id: 41,
    title: "Women Rose Solid Styled Back Fit and Flare Dress",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/productimage/2020/9/18/017cc3d2-fa07-4b99-ac7e-7109cc0dd7f51600383561172-3.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "women",
    category: "Dresses",
    price: 599,
    real_price: 199,
    discount: "60% OFF",
  },
  {
    id: 42,
    title: "Beige Floral Maxi Dress",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/16120950/2021/12/6/de7e417a-207a-4e75-9571-82c00388afcb1638781611141-Kvsfab-Women-Dresses-1881638781610394-3.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "women",
    category: "Dresses",
    price: 1574,
    real_price: 4499,
    discount: "65% OFF",
  },
  {
    id: 43,
    title: "Burgundy Ruched Bodycon Dress",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/10054785/2019/7/3/bdee36e9-d3ac-40e3-9eef-6217cddac2d51562137367369-Veni-Vidi-Vici-Women-Burgundy-Sheath-Dress-7151562137365581-1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "women",
    category: "Dresses",
    price: 945,
    real_price: 1890,
    discount: "50% OFF",
  },
  {
    id: 44,
    title:
      "Women Mustard Yellow Dobby Self Design Fit and Flare Dress with Ruffles",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/13724168/2021/5/31/201b3329-1f9b-4634-ba5e-f5a9e1a5e30a1622475708988-Berrylush-Women-Mustard-Yellow-Dobby-Self-Design-Fit-and-Fla-1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "women",
    category: "Dresses",
    price: 883,
    real_price: 1699,
    discount: "48% OFF",
  },
  {
    id: 45,
    title: "Mauve & Golden Floral Sequinned Saree",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/15443710/2021/9/25/936e7373-f19a-4cf7-b916-bd91b761e3401632560601248-Inddus-Women-Mauve-Embroidered-Saree-with-Blouse-Piece-58816-2.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "women",
    category: "Sarees",
    price: 2495,
    real_price: 5199,
    discount: "52% OFF",
  },
  {
    id: 46,
    title: "Red & Golden Floral Zari Silk Blend Saree",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/productimage/2021/5/25/39c845a8-bea5-4fa1-a1d9-96aba0d90a611621940411719-1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "women",
    category: "Sarees",
    price: 2999,
    real_price: 4999,
    discount: "40% OFF",
  },
  {
    id: 47,
    title: "Olive Green Solid Net Celebrity Saree",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/12631292/2020/10/22/a992641a-5fe6-44ae-abe5-287e6ba051f61603366804643-Inddus-Women-Sarees-1741603366802361-1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "women",
    category: "Sarees",
    price: 1785,
    real_price: 4699,
    discount: "62% OFF",
  },
  {
    id: 48,
    title: "Green & Navy Blue Ethnic Motifs Zari Pure Cotton Kota Saree",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/16762648/2022/1/10/092e635b-a328-484a-8e92-17bbe77297fb1641828436623UnnatiSilksWomenGreenPrinted1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "women",
    category: "Sarees",
    price: 2699,
    real_price: 5398,
    discount: "50% OFF",
  },
  {
    id: 49,
    title: "White Embroidered Sheer Saree",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/13764370/2021/3/16/ba8bc146-2e8b-450f-8ec4-ac0fda6e4af71615883524154KalistawhitecolornetSareewithBlouse1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "women",
    category: "Sarees",
    price: 979,
    real_price: 1999,
    discount: "59% OFF",
  },
  {
    id: 50,
    title: "Yellow & Orange Floral Celebrity Organza Saree",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/14277194/2021/6/15/11c79a9c-cf75-4440-8546-d85bbecb02c31623760533593AnoukYellowOrangeFloralCelebrityOrganzaSaree1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "women",
    category: "Sarees",
    price: 804,
    real_price: 2299,
    discount: "65% OFF",
  },
  {
    id: 51,
    title: "Black & Pink Floral Organza Saree",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/productimage/2021/6/11/379bc356-6f7e-4ee6-97b7-f33dcfda6e2a1623411002808-1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "women",
    category: "Sarees",
    price: 1631,
    real_price: 3399,
    discount: "52% OFF",
  },
  {
    id: 52,
    title: "Blue & Gold-Toned Checked Linen Blend Saree",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/16440958/2021/12/10/71e80f34-db14-4cb3-ab45-2fa2e9fbc62d1639117239994KALINIWomenBlueChecked1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "women",
    category: "Sarees",
    price: 499,
    real_price: 1999,
    discount: "75% OFF",
  },
  {
    id: 53,
    title: "Brown PU Structured Handheld Bag",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/15398610/2021/10/18/a839b66f-f981-4639-8c55-cb21dae9e8601634539285586-Van-Heusen-Women-Handbags-8611634539284955-2.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "women",
    category: "Handbags",
    price: 1499,
    real_price: 2999,
    discount: "50% OFF",
  },
  {
    id: 54,
    title: "Black Textured Handheld Bag",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/10313871/2020/2/25/a63f7b51-61d1-4f5e-9c2e-7f6f162078ae1582622218419-KLEIO-Black-Textured-Handheld-Bag-7911582622216855-1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "women",
    category: "Handbags",
    price: 1259,
    real_price: 2999,
    discount: "58% OFF",
  },
  {
    id: 55,
    title: "Green Croc-Textured Handheld Bag with Detachable Sling Strap",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/11632670/2020/3/16/9a3f8ecd-c381-4478-8201-2624d5358ddb1584351656050-Lino-Perros-Sea-Green-Textured-Handheld-Bag-691584351654721-1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "women",
    category: "Handbags",
    price: 1478,
    real_price: 3695,
    discount: "60% OFF",
  },
  {
    id: 56,
    title: "Mustard Yellow Solid Handheld Bag",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/11154288/2020/2/5/c764e29c-7059-4946-a5c7-252227e927941580896112000-Mast--Harbour-Mustard-Solid-Handheld-Bag-5541580896109922-2.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "women",
    category: "Handbags",
    price: 1749,
    real_price: 3499,
    discount: "50% OFF",
  },
  {
    id: 57,
    title: "Teal Blue Textured Handheld Bag",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/13662482/2021/3/1/f70adf92-64ad-4deb-a887-8d2a5c1e516c1614597667484-Allen-Solly-Women-Handbags-4621614597665551-2.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "women",
    category: "Handbags",
    price: 1559,
    real_price: 2599,
    discount: "40% OFF",
  },
  {
    id: 58,
    title: "Lavender Solid Anne Handheld Bag",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/productimage/2021/4/14/d3ca3e29-858f-4f4b-b873-c33fee8f6b7f1618420413681-2.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "women",
    category: "Handbags",
    price: 2479,
    real_price: 4999,
    discount: "45% OFF",
  },
  {
    id: 59,
    title: "Beige Quilted Handheld Bag",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/8378281/2019/1/9/d668b1bb-e9cf-45b6-9071-9d260bfd5e1a1547017371705-Lino-Perros-Beige-Leatherette-Handbag-3671547017370950-2.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "women",
    category: "Handbags",
    price: 1483,
    real_price: 4495,
    discount: "67% OFF",
  },
  {
    id: 60,
    title:
      "Tan Brown & Yellow Colourblocked Structured Shoulder Bag with Croc Textured Detail",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/15521598/2021/11/15/962f796d-61ba-4e55-8ae0-695de477a1681636973346468CapreseTanBrownYellowColourblockedStructuredShoulderBagwithC1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "women",
    category: "Handbags",
    price: 1079,
    real_price: 2699,
    discount: "60% OFF",
  },
  {
    id: 61,
    title: "Men Blue Solid Straight Kurta",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/10307943/2019/9/18/a0454fba-b9c3-43fe-b19e-5c7f899e0e671568806708674-Anouk-Men-Kurtas-331568806707287-1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "men",
    category: "Ethnicwear",
    price: 629,
    real_price: 1799,
    discount: "65% OFF",
  },
  {
    id: 62,
    title: "Men Beige & Golden Geometric Print Thread Work Straight Kurta",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/14224574/2021/9/7/9f9754b1-e3e3-44a9-a954-3ea2a35226841631013459780-Anouk-Men-Beige--Golden-Geometric-Printed-Pure-Cotton-Thread-3.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "men",
    category: "Ethnicwear",
    price: 809,
    real_price: 2699,
    discount: "70% OFF",
  },
  {
    id: 63,
    title: "Men Navy Blue Kurta & Dhoti Pants with Jacket",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/14808884/2021/7/13/3d089f8d-d4fc-4b3f-96da-dcd42dcef94f1626169093615HangupMenMulticolouredPrintedLayeredKurtawithPatiala4.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "men",
    category: "Ethnicwear",
    price: 3199,
    real_price: 9999,
    discount: "68% OFF",
  },
  {
    id: 64,
    title: "Men Beige and Peach-Coloured Printed Jacquard Satin Nehru Jacket",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/productimage/2021/4/30/bc971f7e-9f29-4c3a-8c38-7c92aeedd8c61619791100191-1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "men",
    category: "Ethnicwear",
    price: 1199,
    real_price: 3999,
    discount: "70% OFF",
  },
  {
    id: 65,
    title: "Men Maroon Pure Cotton Pathani Kurta",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/15471276/2021/9/15/626edec9-c7fe-4b7e-a2ca-b5427625df251631698466959MollyMichelMenMaroonThreadWorkPathaniKurta3.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "men",
    category: "Ethnicwear",
    price: 927,
    real_price: 2899,
    discount: "68% OFF",
  },
  {
    id: 66,
    title: "Men Lime Green Angrakha Kurta with Dhoti Pants",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/16503162/2021/12/13/4fc493a1-23ae-4000-a26f-7c232e237ef81639390920772KISAHMenLimeGreenAngrakhaKurtawithDhotiPants4.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "men",
    category: "Ethnicwear",
    price: 2729,
    real_price: 6999,
    discount: "61% OFF",
  },
  {
    id: 67,
    title: "Men Black Dupion Silk Kurta with Pyjamas & Nehru Jacket",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/productimage/2021/7/9/9140c125-c411-42b1-9447-8439b0b55f0b1625825470905-1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "men",
    category: "Ethnicwear",
    price: 1599,
    real_price: 3999,
    discount: "60% OFF",
  },
  {
    id: 68,
    title: "Men Beige Embroidered Regular Kurta with Churidar",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/15800998/2021/10/11/439bedf4-6bea-4c3a-b73e-00d533a888df1633960834108KISAHMenBeigeEmbroideredRegularKurtawithPyjamas6.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "men",
    category: "Ethnicwear",
    price: 2384,
    real_price: 4499,
    discount: "47% OFF",
  },
  {
    id: 69,
    title: "U S Polo Assn Men Black Textile Walking Shoes",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/15607896/2021/9/24/260d44eb-8cb7-4331-a493-6386953d68e11632489809990SportsShoes1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "men",
    category: "Footwear",
    price: 2579,
    real_price: 4299,
    discount: "40% OFF",
  },
  {
    id: 70,
    title: "Men Brown Nubuck Leather Sneakers",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/14119244/2021/12/8/364f0fcc-594a-426e-a974-be4956b1df591638959439257-Woodland-Men-Casual-Shoes-1321638959438959-1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "men",
    category: "Footwear",
    price: 2970,
    real_price: 3495,
    discount: "15% OFF",
  },
  {
    id: 71,
    title: "Men Blue Driving Shoes",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/14336830/2021/8/13/1598de6a-757e-42b3-8b7f-a31e4beb24791628846280908HIGHLANDERMenBlueDrivingShoes1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "men",
    category: "Footwear",
    price: 774,
    real_price: 1548,
    discount: "50% OFF",
  },
  {
    id: 72,
    title: "mr wonker Men White Angry Birds Colourblocked High-Top Sneakers",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/15713832/2021/10/3/20f7fb97-5c42-4ac6-87bc-b93c4ec353151633222005098mrwonkerMenWhiteAngryBirdsColourblockedHigh-TopSneakers1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "men",
    category: "Footwear",
    price: 739,
    real_price: 3699,
    discount: "80% OFF",
  },
  {
    id: 73,
    title: "Men White Sauve 1.0 Athleisure Shoe",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/11776190/2021/3/19/212548ee-974e-488c-8257-cb6ff3dd669e1616159751820-HRX-by-Hrithik-Roshan-Men-White-Sauve-10-Athleisure-Shoe-166-1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "men",
    category: "Footwear",
    price: 2069,
    real_price: 4599,
    discount: "55% OFF",
  },
  {
    id: 74,
    title:
      "Men Blue & White Lite 3.0 Woven Design Ortholite Foam Sole Running Shoes",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/16561406/2022/1/28/89af8242-eb48-4017-9907-970f8d528ccf1643349786667-Reebok-Men-Sports-Shoes-1111643349786289-1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "men",
    category: "Footwear",
    price: 3679,
    real_price: 4599,
    discount: "20% OFF",
  },
  {
    id: 75,
    title: "Men Black Solid Leather Formal Slip-ons",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/15532330/2021/11/24/cf732f38-cf8a-45ea-9621-44a0b2cba4e31637715177116-Mactree-Men-Black-Solid-Leather-Formal-Slip-ons-355163771517-6.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "men",
    category: "Footwear",
    price: 898,
    real_price: 4490,
    discount: "80% OFF",
  },
  {
    id: 76,
    title: "Men Brown Solid Mid-Top Leather Flat Boots",
    img: "https://assets.myntassets.com/h_1440,q_90,w_1080/v1/assets/images/10299185/2021/11/2/820c256a-be33-4a9d-9adf-d79164fda2281635838235382WoodlandMenBrownSolidMid-TopLeatherFlatBoots1.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    section: "men",
    category: "Footwear",
    price: 3971,
    real_price: 5295,
    discount: "25% OFF",
  },
];
